### ISSUE TITLE
Could you upload the Cyclegan-vc3 baseline's code?

### ISSUE THREAD

**Issue by zhouyh-jlu** [Tinglok/CVC#8]
The cyclegan in CVC baseline is the baseline of CUT. Do you have any feature extraction for wavforms? Like mcep or filterbank? Could you upload the Cyclegan-vc3 baseline's code? Thanks for your help.

And when I running the cyclegan in CVC by VCC2020 database. There are some error:

"UserWarning: Using a target size (torch.Size([1, 80, 135])) that is different to the input size (torch.Size([1, 80, 136])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size. 

The size of tensor a (136) must match the size of tensor b (135) at non-singleton dimension 2"

I found the single wavform feature tensor's size is different. Have you met this kind of error when you run it on VCTK? Thank you so much.

**Comment by zhouyh-jlu** [comment]
> The cyclegan in CVC baseline is the baseline of CUT. Do you have any feature extraction for wavforms? Like mcep or filterbank? Could you upload the Cyclegan-vc3 baseline's code? Thanks for your help.
> 
> And when I running the cyclegan in CVC by VCC2020 database. There are some error:
> 
> _UserWarning: Using a target size (torch.Size([1, 80, 135])) that is different to the input size (torch.Size([1, 80, 136])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
> 
> The size of tensor a (136) must match the size of tensor b (135) at non-singleton dimension 2_
> 
> I found the single wavform feature tensor's size is different. Have you met this kind of error when you run it on VCTK? Thank you so much.

**Comment by Tinglok** [comment]
Sorry for the delay,

For the extraction of mcep and filterbank features, I used this [code](https://github.com/jackaduma/CycleGAN-VC2/blob/master/preprocess_training.py#L26).

For the error in VCC2020 dataset, this is probably due to I commented out codes [here](https://github.com/Tinglok/CVC/blob/main/data/wav_dataset.py#L40), and some utterances in VCC2020 are less than 2s. The intuition is that zero-padding will lead to trivial solution when it comes to the contrastive method. But you could change this [line](https://github.com/Tinglok/CVC/blob/main/data/wav_dataset.py#L42) to `wav = np.tile(wav,10)[:len_pad]`.

Hope this helps!

**Comment by zhouyh-jlu** [comment]
> Sorry for the delay,
> 
> For the extraction of mcep and filterbank features, I used this [code](https://github.com/jackaduma/CycleGAN-VC2/blob/master/preprocess_training.py#L26).
> 
> For the error in VCC2020 dataset, this is probably due to I commented out codes [here](https://github.com/Tinglok/CVC/blob/main/data/wav_dataset.py#L40), and some utterances in VCC2020 are less than 2s. The intuition is that zero-padding will lead to trivial solution when it comes to the contrastive method. But you could change this [line](https://github.com/Tinglok/CVC/blob/main/data/wav_dataset.py#L42) to `wav = np.tile(wav,10)[:len_pad]`.
> 
> Hope this helps!

Thanks for your kind help. I will try!
